### ISSUE TITLE
TAS5754 or TAS5780 and programmability

### ISSUE THREAD

**Issue by infnorm** [philippe44/SqueezeAMP#1]
Your project is amazing, I'm wondering if there is any advantage for the TAS5780 vs TAS5754. It seems TAS5780 is fixed function and TAS5754 is more programmable DSP. Is it possible to program the DSP without the TI realpath software or to use the AMP without it? It seems like you need to setup a program by i2c for the TAS5754, and not all the registers are documented to setup a HybridFlow program. It seems like you could maybe get it working by setting the register on the top of page 74 http://www.ti.com/lit/ds/slas987/slas987.pdf 
i.e.
P0-R43 to "fixed process flow with user parameters" 0 0 1 1 0

**Comment by philippe44** [comment]
Thank you :-)

Initially I added TAS5780 because there was no way to switch off the analogue part of TAS5754 and keep the DAC output (headset) on TAS5754 but I finally found a way, so both are fine.

Unfortunately, to answer your question, I've not been able to do much progress on hybrid flow and how to use it. I've been very busy with updating the HW and developping the SW (I need to push a few cool updates)

Now I'm not sure by what you mean by "Is it possible ... to use the AMP without it". The AMP works perfectly fine w/o using TI realpath. It works out of the box, no need of TI software. Realpath allows you to tweaks things, which I'd like to do at some point, but don't worry, it works very fine just like that

**Comment by infnorm** [comment]
Thanks for the info!

1. by switch off the analog you mean turn off the power amplification so you are just using the amp.

2. as far as "is it possible..to use the AMP without it..." I am surprised as the datasheet and application guide doesn't seem to indicate you can use the tas5754 without using the evaluation 
board to get a program. Their software is kind of stupid in that you need an evaluation board to extract a program into a header that has a dump of the registers that can be reloaded from the mcu. But I guess it can work because the default mode on bootup is configured in a way that it just uses some default program or bypasses the dsp portion. It's kind of sad that TI hasn't made the software situation friendly like analog with the adau1701 and other stuff and sigma studio.

**Comment by philippe44** [comment]
1- I meant there is a DAC output on the TAS that you loop-in. I use it for line-out but I also wanted to have the option to switch off the built-in power amplifier when the jack is inserted, but still have the analogue out of course. And it was a bit tricky.

2- I agree, but the good thing is that I can re-insure you that you don't need any tool to make it work. You just have to send a few commands on the I2C bus to configure it your way and that's very simple (it's all there in my SW project). No need to download complicated audio path/config data. It's mainly PLL config and of course volume management

**Comment by philippe44** [comment]
Closed for inactivity
